/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package keystrokefinal;

import java.util.ArrayList;
import java.awt.event.KeyListener;

import java.awt.event.KeyEvent;

import javax.swing.JFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author Sachin
 */
public class LogInForm extends javax.swing.JFrame {

    /**
     * Creates new form LogInForm
     */
    static ArrayList<Long> timeListLogIn;
    static ArrayList<Long> timeListLogIn1;
    long flyTimeLogIn;
    long pressTimeLogIn;
    long startTimeLogIn;
    long startTimeLogIn1;
    public LogInForm() {
        initComponents();
        timeListLogIn=new ArrayList<Long>();
        timeListLogIn1=new ArrayList<Long>();
        keyCodeLogIn.addKeyListener(new KeyListener() {
    @Override
    public void keyTyped(KeyEvent event) {
        
    }
    @Override
    public void keyPressed(KeyEvent event) {
        
        startTimeLogIn = System.currentTimeMillis();
        flyTimeLogIn = System.currentTimeMillis()-startTimeLogIn1; 
        timeListLogIn1.add(flyTimeLogIn);
    }
    @Override
    public void keyReleased(KeyEvent event) {
        startTimeLogIn1 = System.currentTimeMillis(); 
        pressTimeLogIn = System.currentTimeMillis()-startTimeLogIn;
        timeListLogIn.add(pressTimeLogIn);
       
       
    }
    
});     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameLogIn = new javax.swing.JTextField();
        keyCodeLogIn = new javax.swing.JTextField();
        logInButton = new javax.swing.JButton();
        registerNewButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("UserName");

        jLabel2.setText("Password");

        userNameLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameLogInActionPerformed(evt);
            }
        });

        keyCodeLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyCodeLogInActionPerformed(evt);
            }
        });

        logInButton.setText("LogIn");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        registerNewButton.setText("SignUp");
        registerNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNewButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Sign Up here!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(logInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(registerNewButton, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(userNameLogIn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keyCodeLogIn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(keyCodeLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logInButton)
                    .addComponent(registerNewButton))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keyCodeLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyCodeLogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyCodeLogInActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(SignUpForm.sendPasswordSignUp()+ "  "+keyCodeLogIn.getText()+" "+ SignUpForm.sendPasswordSignUp().equals(keyCodeLogIn.getText()) );
        if (!SignUpForm.sendPasswordSignUp().equals(keyCodeLogIn.getText())){
            JFrame frame = new JFrame("OutPut message");
            JOptionPane.showMessageDialog(frame, "Wrong Password. Please Try Again!");  
        }
        else if(Compare.checkForSimilarity(userNameLogIn.getText(),timeListLogIn,timeListLogIn1)==true){
            JFrame frame = new JFrame("OutPut message");
            JOptionPane.showMessageDialog(frame, "successfully logged in. Welcome " + userNameLogIn.getText());  
        }
        else{
            JFrame frame = new JFrame("OutPut message");
            JOptionPane.showMessageDialog(frame, "Failed to logged in. Try again!"); 
        }
        timeListLogIn1= new ArrayList<Long>();
        timeListLogIn= new ArrayList<Long>();
        userNameLogIn.setText("");
        keyCodeLogIn.setText("");
    }//GEN-LAST:event_logInButtonActionPerformed
    
    private void registerNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNewButtonActionPerformed
        // TODO add your handling code here:
        //userNameLogIn.setText("");
        //keyCodeLogIn.setText("");
        KeyStrokeFinal.setSignUpForm();
        //SignUpForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerNewButtonActionPerformed

    private void userNameLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameLogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField keyCodeLogIn;
    private javax.swing.JButton logInButton;
    private javax.swing.JButton registerNewButton;
    private javax.swing.JTextField userNameLogIn;
    // End of variables declaration//GEN-END:variables
}
